Repository R2D2-2023/Backend, pull requests merged in 2023-07, with the labels that each got.

#58 Particulate matter chart
  pyscripts/gendata_10s_interval.py
  routes.py
  static/bootstrap/css/style_charts.css
  static/bootstrap/js/charts_script.js
  templates/charts.html
  templates/index.html
Labels: enhancement

#61 head and header cleaned up, fixed header overlap with page contents
  static/bootstrap/css/style_charts.css
  static/bootstrap/css/style_email.css
  static/bootstrap/css/style_header.css
  static/bootstrap/css/style_index.css
  static/bootstrap/css/style_index_oud.css
  static/bootstrap/css/style_lege_pagina.css
  static/bootstrap/css/style_login.css
  static/bootstrap/js/script.js
  templates/charts.html
  templates/email.html
  templates/head.html
  templates/header.html
  templates/index.html
  templates/login.html
Labels: enhancement

#47 Working notification template
  models.py
  routes.py
  static/bootstrap/css/style_index.css
  static/bootstrap/css/style_notifs_test.css
  static/bootstrap/js/notifications.js
  templates/index.html
  templates/notif_test.html
Labels: enhancement

#59 Bugfix/repair unittests pipelines
  .github/workflows/pytest.yml
  .github/workflows/static_code_check.yml
  migrations/README
  migrations/alembic.ini
  migrations/env.py
  migrations/script.py.mako
  migrations/versions/f5c466ac9441_.py
  models.py
  pyscripts/gendata_instant.py
  routes.py
  templates/email.html
  tests/test_helloworld.py
Labels: bug, enhancement

#62 De tijd van de notificaties is gefixt
  static/bootstrap/js/notifications.js
Labels: bug

#63 Changed english to dutch and changed PM chart colors
  templates/charts.html
  templates/email.html
  templates/posts.html
Labels: enhancement

#65 Added documentation for all functions
  app.py
  models.py
  routes.py
  runbooks/payload_decoder.js
  static/bootstrap/css/style_index_oud.css
  static/bootstrap/css/style_lege_pagina.css
  static/bootstrap/css/style_notifs_test.css
  static/bootstrap/js/charts_script.js
  static/bootstrap/js/index_script.js
  static/bootstrap/js/notifications.js
  templates/charts.html
  templates/email.html
  templates/header.html
  templates/index.html
  templates/index_oud.html
  templates/lege_pagina.html
  templates/notif_test.html
  tests/test_helloworld.py
Labels: documentation

#66 Update README.md
  README.md
Labels: documentation

#69 Disabled hovering
  pyscripts/gendata_10s_interval.py
  static/bootstrap/css/style_charts.css
Labels: bug
